/**
 * `opencode-plugin` scaffolder — installs the dev-link warning plugin into
 * `<repoRoot>/.opencode/plugins/webpresso-dev-link.js`.
 *
 * Why a plugin: opencode is the third runtime alongside Claude Code and
 * Codex CLI. Per opencode docs (opencode.ai/docs/plugins) it loads
 * JavaScript/TypeScript files from `.opencode/plugins/` automatically at
 * startup. There is no shell-hook surface — opencode is a plugin-based
 * extensibility model (event handlers, tool wrappers, compaction hooks).
 *
 * What this plugin does: shells out to `wp-check-dev-link` (the same bin
 * Claude Code and Codex run as a SessionStart hook) on `session.created`
 * and on the `experimental.session.compacting` event. If the bin emits a
 * non-empty additionalContext envelope, the plugin:
 *   1. Writes a clearly visible warning to `process.stderr` (TUI-visible)
 *   2. Pushes the same message into `output.context` during compaction so
 *      it survives compacted sessions
 *
 * Plain JavaScript (not TypeScript) — keeps the plugin runtime-portable
 * with zero deps. opencode auto-installs deps declared in
 * `.opencode/package.json` (per docs); we don't add any.
 *
 * Idempotent: if the plugin file already exists with identical content,
 * leaves it alone. Re-runs of `wp setup` refresh this generated file to the
 * current webpresso-owned content.
 */
import { join } from 'node:path'

import { type MergeOptions, type MergeResult, writeFileMerged } from '#cli/commands/init/merge'

export const OPENCODE_PLUGIN_RELATIVE_PATH = '.opencode/plugins/webpresso-dev-link.js'

export interface ScaffoldOpencodePluginInput {
  repoRoot: string
  options: MergeOptions
}

export const OPENCODE_PLUGIN_CONTENT = `// Generated by webpresso (\`wp setup\`).
//
// Cross-runtime dev-link breakage warning for opencode. Mirrors the
// SessionStart hook installed for Claude Code and Codex by shelling out
// to the same \`wp-check-dev-link\` bin shipped with webpresso.
//
// The plugin emits the warning via stderr (visible in the opencode TUI)
// on session.created, and pushes the same message into output.context
// during compaction so it survives compacted sessions.
//
// Re-run \`wp setup\` to update this file. Delete it to opt out.

const HOOK_BIN = './node_modules/.bin/wp-check-dev-link'

async function detectBreakage($, directory) {
  const result = await $\`bun \${HOOK_BIN}\`.cwd(directory).quiet().nothrow()
  if (result.exitCode !== 0) return null
  const stdout = result.stdout.toString().trim()
  if (stdout === '') return null
  try {
    const envelope = JSON.parse(stdout)
    return envelope?.hookSpecificOutput?.additionalContext ?? null
  } catch {
    return null
  }
}

export const WebpressoDevLinkPlugin = async ({ $, directory }) => {
  const reportIfBroken = async () => {
    const message = await detectBreakage($, directory)
    if (message !== null) process.stderr.write(\`\\n[opencode] \${message}\\n\\n\`)
    return message
  }

  await reportIfBroken()

  return {
    event: async ({ event }) => {
      if (event?.type === 'session.created') await reportIfBroken()
    },
    'experimental.session.compacting': async (_input, output) => {
      const message = await reportIfBroken()
      if (message !== null && output && Array.isArray(output.context)) {
        output.context.push(message)
      }
    },
  }
}
`

export function scaffoldOpencodePlugin(input: ScaffoldOpencodePluginInput): MergeResult {
  const targetPath = join(input.repoRoot, OPENCODE_PLUGIN_RELATIVE_PATH)
  return writeFileMerged(targetPath, OPENCODE_PLUGIN_CONTENT, {
    ...input.options,
    ownership: 'generated-whole-file',
  })
}
