/**
 * spec-kit field map — shared headers and templates.
 * No string literals are duplicated across emitters; all shared content lives here.
 */

import type { ParsedBlueprintForDb } from '#db/parser/blueprint-db-parser'

export const SPEC_KIT_HEADER_COMMENT =
  '<!-- Generated by wp blueprint export --format spec-kit. Do not edit manually. -->'

export function titleLine(parsed: ParsedBlueprintForDb, suffix: string): string {
  return `# ${parsed.title} — ${suffix}`
}

export function overviewSection(parsed: ParsedBlueprintForDb): string {
  const first = firstParagraphs(parsed)
  return `## Overview\n\n${first}`
}

export function firstParagraphs(parsed: ParsedBlueprintForDb): string {
  // Extract up to 2 non-empty paragraphs that aren't frontmatter-style headers
  const lines = parsed.title ? [parsed.title] : []
  if (parsed.tags.length > 0) {
    lines.push(`Tags: ${parsed.tags.join(', ')}`)
  }
  if (parsed.complexity) {
    lines.push(`Complexity: ${parsed.complexity}`)
  }
  return lines.length > 0 ? lines.join('\n') : parsed.slug
}

export function taskIdLabel(index: number, waveOffset: number = 0): string {
  const n = index + 1 + waveOffset
  return `T${String(n).padStart(3, '0')}`
}

export const REVIEW_CHECKLIST = `## Review Checklist

- [ ] All edge cases documented
- [ ] Risks mitigated
- [ ] Tasks have acceptance criteria`
